version: '3.3'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - '13306:3306'
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
